#!/bin/bash
set -e

SERVER_DIR="/home/minecraft/server"
DATA_DIR="/home/minecraft/data"
PLUGINS_DIR="/home/minecraft/plugins"

echo "=========================================="
echo "  ArcadeNode - Minecraft Server"
echo "=========================================="
echo "[INFO] Server Type: ${SERVER_TYPE}"
echo "[INFO] Minecraft Version: ${MC_VERSION}"

# Create data directories
mkdir -p "${DATA_DIR}/world"
mkdir -p "${DATA_DIR}/world_nether"
mkdir -p "${DATA_DIR}/world_the_end"
mkdir -p "${DATA_DIR}/logs"
mkdir -p "${PLUGINS_DIR}"

cd ${SERVER_DIR}

# Download server JAR based on type
SERVER_JAR="${SERVER_DIR}/server.jar"

download_paper() {
    echo "[INFO] Downloading Paper ${MC_VERSION}..."
    
    # Get the latest build number if not specified
    if [ "${PAPER_BUILD}" = "latest" ]; then
        PAPER_BUILD=$(curl -s "https://api.papermc.io/v2/projects/paper/versions/${MC_VERSION}" | jq -r '.builds[-1]')
    fi
    
    if [ -z "${PAPER_BUILD}" ] || [ "${PAPER_BUILD}" = "null" ]; then
        echo "[ERROR] Failed to get Paper build for version ${MC_VERSION}"
        exit 1
    fi
    
    DOWNLOAD_URL="https://api.papermc.io/v2/projects/paper/versions/${MC_VERSION}/builds/${PAPER_BUILD}/downloads/paper-${MC_VERSION}-${PAPER_BUILD}.jar"
    
    echo "[INFO] Downloading Paper build ${PAPER_BUILD}..."
    curl -L -o "${SERVER_JAR}" "${DOWNLOAD_URL}"
}

download_vanilla() {
    echo "[INFO] Downloading Vanilla ${MC_VERSION}..."
    
    # Get version manifest
    VERSION_MANIFEST=$(curl -s "https://launchermeta.mojang.com/mc/game/version_manifest.json")
    VERSION_URL=$(echo "${VERSION_MANIFEST}" | jq -r ".versions[] | select(.id == \"${MC_VERSION}\") | .url")
    
    if [ -z "${VERSION_URL}" ] || [ "${VERSION_URL}" = "null" ]; then
        echo "[ERROR] Version ${MC_VERSION} not found"
        exit 1
    fi
    
    VERSION_DATA=$(curl -s "${VERSION_URL}")
    SERVER_URL=$(echo "${VERSION_DATA}" | jq -r '.downloads.server.url')
    
    curl -L -o "${SERVER_JAR}" "${SERVER_URL}"
}

download_spigot() {
    echo "[INFO] Downloading Spigot ${MC_VERSION}..."
    
    # Note: Spigot requires BuildTools to build, using Paper as fallback
    echo "[WARN] Spigot requires BuildTools. Using Paper instead..."
    download_paper
}

# Check if we need to download/update the server
if [ ! -f "${SERVER_JAR}" ]; then
    case "${SERVER_TYPE}" in
        paper)
            download_paper
            ;;
        vanilla)
            download_vanilla
            ;;
        spigot)
            download_spigot
            ;;
        *)
            echo "[ERROR] Unknown server type: ${SERVER_TYPE}"
            exit 1
            ;;
    esac
fi

# Accept EULA
echo "[INFO] Accepting EULA..."
echo "eula=true" > "${SERVER_DIR}/eula.txt"

# Generate server.properties
echo "[INFO] Generating server.properties..."
cat > "${SERVER_DIR}/server.properties" << EOF
# Minecraft Server Properties
# Generated by ArcadeNode

# Server
server-port=${SERVER_PORT}
server-name=${SERVER_NAME}
motd=${MOTD}
max-players=${MAX_PLAYERS}
difficulty=${DIFFICULTY}
gamemode=${GAMEMODE}
level-name=${LEVEL_NAME}
level-seed=${LEVEL_SEED}
level-type=${LEVEL_TYPE}
max-world-size=${MAX_WORLD_SIZE}

# Performance
view-distance=${VIEW_DISTANCE}
simulation-distance=${SIMULATION_DISTANCE}
network-compression-threshold=256

# Security
online-mode=${ONLINE_MODE}
white-list=${WHITE_LIST}
enforce-whitelist=${ENFORCE_WHITELIST}
spawn-protection=${SPAWN_PROTECTION}

# Gameplay
pvp=${PVP}
allow-nether=${ALLOW_NETHER}
allow-flight=${ALLOW_FLIGHT}
spawn-animals=${SPAWN_ANIMALS}
spawn-monsters=${SPAWN_MONSTERS}
spawn-npcs=${SPAWN_NPCS}
generate-structures=${GENERATE_STRUCTURES}
enable-command-block=${ENABLE_COMMAND_BLOCK}

# RCON
enable-rcon=${ENABLE_RCON}
rcon.port=${RCON_PORT}
rcon.password=${RCON_PASSWORD}
broadcast-rcon-to-ops=true

# Query
enable-query=${ENABLE_QUERY}
query.port=${SERVER_PORT}

# Misc
force-gamemode=false
hardcore=false
hide-online-players=false
prevent-proxy-connections=false
resource-pack=
resource-pack-sha1=
sync-chunk-writes=true
use-native-transport=true
EOF

# Link world directories
ln -sfn "${DATA_DIR}/world" "${SERVER_DIR}/world" 2>/dev/null || true
ln -sfn "${DATA_DIR}/world_nether" "${SERVER_DIR}/world_nether" 2>/dev/null || true
ln -sfn "${DATA_DIR}/world_the_end" "${SERVER_DIR}/world_the_end" 2>/dev/null || true
ln -sfn "${DATA_DIR}/logs" "${SERVER_DIR}/logs" 2>/dev/null || true
ln -sfn "${PLUGINS_DIR}" "${SERVER_DIR}/plugins" 2>/dev/null || true

# Set up ops if specified
if [ -n "${OPS}" ]; then
    echo "[INFO] Setting up operators..."
    # Convert comma-separated list to JSON array
    echo "[" > "${SERVER_DIR}/ops.json"
    IFS=',' read -ra OP_ARRAY <<< "${OPS}"
    for i in "${!OP_ARRAY[@]}"; do
        OP="${OP_ARRAY[$i]}"
        if [ $i -gt 0 ]; then
            echo "," >> "${SERVER_DIR}/ops.json"
        fi
        cat >> "${SERVER_DIR}/ops.json" << OPENTRY
    {
        "uuid": "",
        "name": "${OP}",
        "level": 4,
        "bypassesPlayerLimit": true
    }
OPENTRY
    done
    echo "]" >> "${SERVER_DIR}/ops.json"
fi

# Download server icon if URL provided
if [ -n "${ICON_URL}" ]; then
    echo "[INFO] Downloading server icon..."
    curl -L -o "${SERVER_DIR}/server-icon.png" "${ICON_URL}" || echo "[WARN] Failed to download icon"
fi

echo ""
echo "[INFO] Starting Minecraft Server..."
echo "[INFO] Server Type: ${SERVER_TYPE}"
echo "[INFO] Version: ${MC_VERSION}"
echo "[INFO] Max Players: ${MAX_PLAYERS}"
echo "[INFO] Game Port: ${SERVER_PORT}"
echo "[INFO] RCON Port: ${RCON_PORT}"
echo "[INFO] Memory: ${MIN_RAM} - ${MAX_RAM}"
echo ""

# Start the server
exec java \
    -Xms${MIN_RAM} \
    -Xmx${MAX_RAM} \
    -XX:+UseG1GC \
    -XX:+ParallelRefProcEnabled \
    -XX:MaxGCPauseMillis=200 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+DisableExplicitGC \
    -XX:+AlwaysPreTouch \
    -XX:G1NewSizePercent=30 \
    -XX:G1MaxNewSizePercent=40 \
    -XX:G1HeapRegionSize=8M \
    -XX:G1ReservePercent=20 \
    -XX:G1HeapWastePercent=5 \
    -XX:G1MixedGCCountTarget=4 \
    -XX:InitiatingHeapOccupancyPercent=15 \
    -XX:G1MixedGCLiveThresholdPercent=90 \
    -XX:G1RSetUpdatingPauseTimePercent=5 \
    -XX:SurvivorRatio=32 \
    -XX:+PerfDisableSharedMem \
    -XX:MaxTenuringThreshold=1 \
    -Dusing.aikars.flags=https://mcflags.emc.gs \
    -Daikars.new.flags=true \
    -jar "${SERVER_JAR}" \
    --nogui \
    "$@"
