#!/bin/bash
set -e

SERVER_DIR="/home/bedrock/server"
DATA_DIR="/home/bedrock/data"

echo "=========================================="
echo "  ArcadeNode - Minecraft Bedrock Server"
echo "=========================================="

# Create data directories
mkdir -p "${DATA_DIR}/worlds"
mkdir -p "${DATA_DIR}/resource_packs"
mkdir -p "${DATA_DIR}/behavior_packs"

cd ${SERVER_DIR}

# Function to download Bedrock server
download_bedrock() {
    echo "[INFO] Checking for Bedrock Dedicated Server updates..."
    
    # Get the download page to find the latest version
    if [ "${VERSION}" = "LATEST" ]; then
        echo "[INFO] Fetching latest version..."
        # Try to get version from the official download page
        DOWNLOAD_URL=$(curl -s -A "Mozilla/5.0" "https://www.minecraft.net/en-us/download/server/bedrock" | \
            grep -o 'https://minecraft.azureedge.net/bin-linux/bedrock-server-[0-9.]*\.zip' | head -1)
        
        if [ -z "${DOWNLOAD_URL}" ]; then
            # Fallback: use a known working version format
            echo "[WARN] Could not detect latest version, using fallback method..."
            # Try alternative API endpoint
            DOWNLOAD_URL="https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.44.01.zip"
        fi
    else
        DOWNLOAD_URL="https://minecraft.azureedge.net/bin-linux/bedrock-server-${VERSION}.zip"
    fi
    
    echo "[INFO] Download URL: ${DOWNLOAD_URL}"
    
    # Check if we need to download
    CURRENT_VERSION=""
    if [ -f "${SERVER_DIR}/.version" ]; then
        CURRENT_VERSION=$(cat "${SERVER_DIR}/.version")
    fi
    
    # Extract version from URL
    NEW_VERSION=$(echo "${DOWNLOAD_URL}" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' || echo "unknown")
    
    if [ "${CURRENT_VERSION}" != "${NEW_VERSION}" ] || [ ! -f "${SERVER_DIR}/bedrock_server" ]; then
        echo "[INFO] Downloading Bedrock Server version ${NEW_VERSION}..."
        
        # Download to temp file
        curl -L -A "Mozilla/5.0" -o /tmp/bedrock-server.zip "${DOWNLOAD_URL}"
        
        # Backup existing config if it exists
        if [ -f "${SERVER_DIR}/server.properties" ]; then
            cp "${SERVER_DIR}/server.properties" /tmp/server.properties.bak
        fi
        if [ -f "${SERVER_DIR}/allowlist.json" ]; then
            cp "${SERVER_DIR}/allowlist.json" /tmp/allowlist.json.bak
        fi
        if [ -f "${SERVER_DIR}/permissions.json" ]; then
            cp "${SERVER_DIR}/permissions.json" /tmp/permissions.json.bak
        fi
        
        # Extract
        unzip -o /tmp/bedrock-server.zip -d ${SERVER_DIR}
        rm /tmp/bedrock-server.zip
        
        # Restore configs if they existed
        if [ -f /tmp/server.properties.bak ]; then
            mv /tmp/server.properties.bak "${SERVER_DIR}/server.properties"
        fi
        if [ -f /tmp/allowlist.json.bak ]; then
            mv /tmp/allowlist.json.bak "${SERVER_DIR}/allowlist.json"
        fi
        if [ -f /tmp/permissions.json.bak ]; then
            mv /tmp/permissions.json.bak "${SERVER_DIR}/permissions.json"
        fi
        
        # Save version
        echo "${NEW_VERSION}" > "${SERVER_DIR}/.version"
        
        # Make executable
        chmod +x "${SERVER_DIR}/bedrock_server"
        
        echo "[INFO] Bedrock Server ${NEW_VERSION} installed successfully"
    else
        echo "[INFO] Bedrock Server ${CURRENT_VERSION} is up to date"
    fi
}

# Download/update server
download_bedrock

# Link world directories for persistence
rm -rf "${SERVER_DIR}/worlds" 2>/dev/null || true
ln -sfn "${DATA_DIR}/worlds" "${SERVER_DIR}/worlds"

# Link resource and behavior packs
rm -rf "${SERVER_DIR}/resource_packs" 2>/dev/null || true
rm -rf "${SERVER_DIR}/behavior_packs" 2>/dev/null || true
ln -sfn "${DATA_DIR}/resource_packs" "${SERVER_DIR}/resource_packs"
ln -sfn "${DATA_DIR}/behavior_packs" "${SERVER_DIR}/behavior_packs"

# Generate server.properties
echo "[INFO] Generating server.properties..."
cat > "${SERVER_DIR}/server.properties" << EOF
# Minecraft Bedrock Server Properties
# Generated by ArcadeNode

server-name=${SERVER_NAME}
gamemode=${GAMEMODE}
force-gamemode=false
difficulty=${DIFFICULTY}
allow-cheats=${ALLOW_CHEATS}
max-players=${MAX_PLAYERS}
online-mode=${ONLINE_MODE}
allow-list=${WHITE_LIST}
server-port=${SERVER_PORT}
server-portv6=${SERVER_PORTV6}
enable-lan-visibility=true
view-distance=${VIEW_DISTANCE}
tick-distance=${TICK_DISTANCE}
player-idle-timeout=${PLAYER_IDLE_TIMEOUT}
max-threads=${MAX_THREADS}
level-name=${LEVEL_NAME}
level-seed=${LEVEL_SEED}
level-type=${LEVEL_TYPE}
default-player-permission-level=${DEFAULT_PLAYER_PERMISSION_LEVEL}
texturepack-required=${TEXTUREPACK_REQUIRED}
content-log-file-enabled=${CONTENT_LOG_FILE_ENABLED}
compression-threshold=${COMPRESSION_THRESHOLD}
compression-algorithm=${COMPRESSION_ALGORITHM}
server-authoritative-movement=${SERVER_AUTHORITATIVE_MOVEMENT}
player-movement-score-threshold=${PLAYER_MOVEMENT_SCORE_THRESHOLD}
player-movement-action-direction-threshold=${PLAYER_MOVEMENT_ACTION_DIRECTION_THRESHOLD}
player-movement-distance-threshold=${PLAYER_MOVEMENT_DISTANCE_THRESHOLD}
player-movement-duration-threshold-in-ms=${PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS}
correct-player-movement=${CORRECT_PLAYER_MOVEMENT}
server-authoritative-block-breaking=${SERVER_AUTHORITATIVE_BLOCK_BREAKING}
chat-restriction=${CHAT_RESTRICTION}
disable-player-interaction=${DISABLE_PLAYER_INTERACTION}
client-side-chunk-generation-enabled=${CLIENT_SIDE_CHUNK_GENERATION_ENABLED}
block-network-ids-are-hashes=${BLOCK_NETWORK_IDS_ARE_HASHES}
disable-persona=${DISABLE_PERSONA}
disable-custom-skins=${DISABLE_CUSTOM_SKINS}
server-build-radius-ratio=${SERVER_BUILD_RADIUS_RATIO}
EOF

# Set up allowlist if specified
if [ -n "${ALLOW_LIST_USERS}" ]; then
    echo "[INFO] Setting up allowlist..."
    echo "[" > "${SERVER_DIR}/allowlist.json"
    IFS=',' read -ra USERS <<< "${ALLOW_LIST_USERS}"
    FIRST=true
    for USER in "${USERS[@]}"; do
        USER=$(echo "${USER}" | xargs)  # Trim whitespace
        if [ -n "${USER}" ]; then
            if [ "${FIRST}" = true ]; then
                FIRST=false
            else
                echo "," >> "${SERVER_DIR}/allowlist.json"
            fi
            cat >> "${SERVER_DIR}/allowlist.json" << USERENTRY
    {
        "name": "${USER}"
    }
USERENTRY
        fi
    done
    echo "]" >> "${SERVER_DIR}/allowlist.json"
fi

# Set up operators/permissions if specified
if [ -n "${OPS}" ]; then
    echo "[INFO] Setting up operators..."
    echo "[" > "${SERVER_DIR}/permissions.json"
    IFS=',' read -ra OP_ARRAY <<< "${OPS}"
    FIRST=true
    for OP in "${OP_ARRAY[@]}"; do
        OP=$(echo "${OP}" | xargs)  # Trim whitespace
        if [ -n "${OP}" ]; then
            if [ "${FIRST}" = true ]; then
                FIRST=false
            else
                echo "," >> "${SERVER_DIR}/permissions.json"
            fi
            cat >> "${SERVER_DIR}/permissions.json" << OPENTRY
    {
        "permission": "operator",
        "xuid": "${OP}"
    }
OPENTRY
        fi
    done
    echo "]" >> "${SERVER_DIR}/permissions.json"
fi

echo ""
echo "[INFO] Starting Minecraft Bedrock Server..."
echo "[INFO] Server Name: ${SERVER_NAME}"
echo "[INFO] Max Players: ${MAX_PLAYERS}"
echo "[INFO] Game Port: ${SERVER_PORT}/udp"
echo "[INFO] IPv6 Port: ${SERVER_PORTV6}/udp"
echo "[INFO] Gamemode: ${GAMEMODE}"
echo "[INFO] Difficulty: ${DIFFICULTY}"
echo ""

# Set library path
export LD_LIBRARY_PATH="${SERVER_DIR}"

# Start the server
exec "${SERVER_DIR}/bedrock_server"
